### ISSUE TITLE
这个和git的submodule 有什么区别

### ISSUE THREAD

**Issue by top2015** [EastWoodYang/Gradle-Repo#6]
r't

**Comment by EastWoodYang** [comment]
submodule: A submodule is a repository embedded inside another repository. The submodule has its own history; the repository it is embedded in is called a superproject.
-------------------------------------
Gradle Repo is a Gradle plugin. it helps us manage multiple Git repositories and dependencies between modules.
😁

**Comment by EastWoodYang** [comment]
以插件+XML的方式，或许方便些吧，额外还处理了模块依赖关系 😬

**Comment by top2015** [comment]
:+1::+1::+1:
